### ISSUE TITLE
Error after updating to version 2023.5.0

### ISSUE THREAD

**Issue by gajotnt** [jello1974/duosidaEV-home-assistant#3]
After updating to latest version, the integration fails do start and gives this error -.-

```
Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/duosida/__init__.py:94
Integration: Duosida ([documentation](https://github.com/jello1974/duosidaEV-home-assistant), [issues](https://github.com/jello1974/duosidaEV-home-assistant/issues))
First occurred: 8:51:46 PM (4 occurrences)
Last logged: 8:53:16 PM

Error setting up entry WallboxDuoSida for duosida
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/duosida/__init__.py", line 94, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by jello1974** [comment]
Update pls.

**Comment by gajotnt** [comment]
Man you're great!!! where can i make a donation? :)

**Comment by jello1974** [comment]
No need my friend. Just enjoy.
