### ISSUE TITLE
Invalid config after updating

### ISSUE THREAD

**Issue by ArjanTel** [jello1974/duosidaEV-home-assistant#8]
HA Versions:
Core - 2024.2.1
Supervisor - 2024.01.1
Operating System - 11.5
Frontend - 20240207.1

![image](https://github.com/jello1974/duosidaEV-home-assistant/assets/9843407/b4ce3cb4-778a-4905-b20a-4c4861b63caf)

`Logger: homeassistant.setup
Source: setup.py:251
First occurred: 13:07:34 (1 occurrences)
Last logged: 13:07:34

Setup failed for custom integration 'duosida': Unable to import component: Exception importing custom_components.duosida
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/duosida/__init__.py", line 27, in <module>
    from .coordinator import DeviceDataUpdateCoordinator
  File "/config/custom_components/duosida/coordinator.py", line 12, in <module>
    from .duosida import DuosidaDevice
  File "/config/custom_components/duosida/duosida.py", line 375, in <module>
    class DuosidaBaseEntityDescription(EntityDescription, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 835, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.duosida
`

`Logger: homeassistant.loader
Source: loader.py:827
First occurred: 13:07:34 (1 occurrences)
Last logged: 13:07:34

Unexpected exception importing component custom_components.duosida
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/duosida/__init__.py", line 27, in <module>
    from .coordinator import DeviceDataUpdateCoordinator
  File "/config/custom_components/duosida/coordinator.py", line 12, in <module>
    from .duosida import DuosidaDevice
  File "/config/custom_components/duosida/duosida.py", line 375, in <module>
    class DuosidaBaseEntityDescription(EntityDescription, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
`

**Comment by jello1974** [comment]
I need more data in order to troubleshoot this. Is your first instalation? It worked but not working anymore after update?
On my home assistant istance works just fine...

**Comment by ArjanTel** [comment]
I was on an older version from last december. Updated it in January but it broke this integration. Reverted back to the older HA version and this integration worked again. Decided to try again when a newer HA version became available but same story.

I will try to remove it and install it again tomorrow and report back.

**Comment by ArjanTel** [comment]
Removed the integration by deleting the folder from /custom_integrations because deleting it from the integrations menu didn't do anything.
Restarted HA
Downloaded the zip and copied the "duosida" folder back into the /custom_integrations folder because I cannot find it in the HACS store even though you mention it is in there in the instructions.
Restarted HA
Tried to add it again via the button in the integrations menu and searching for duosida.
Found it and after adding it I filled in my email and password correctly.
The following screen was this:
![image](https://github.com/jello1974/duosidaEV-home-assistant/assets/9843407/961c536e-806d-4ad4-8de3-5a9c11d5c6f0)

Clicking anything just results the message going away and the integration not installed.
